# Generated by Django 4.2.3 on 2023-07-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('raw_data', models.JSONField()),
                ('images', models.JSONField()),
            ],
            options={
                'db_table': 'pereval_added',
            },
        ),
    ]
