# Generated by Django 4.2.3 on 2023-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0006_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
